version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"